// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, create_at, update_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, create_at, update_at
`

type CreateUserParams struct {
	ID       uuid.UUID
	Name     string
	CreateAt time.Time
	UpdateAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.CreateAt,
		arg.UpdateAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}
